// management actions
export const MANAGEMENT_ACTION_FOO = 'MANAGEMENT_ACTION_FOO';
export const ORGANISATION_ACTION_SET = 'ORGANISATION_ACTION_SET';

// auth actions
export const AUTH_ACTION_SET_ORGANIZATION = 'AUTH_ACTION_SET_ORGANIZATION';
export const AUTH_ACTION_SET_USER = 'AUTH_ACTION_SET_USER';
export const AUTH_ACTION_SET_TOKEN = 'AUTH_ACTION_SET_TOKEN'
export const AUTH_ACTION_LOGIN = 'AUTH_ACTION_LOGIN'

